#!/usr/bin/env python3
from __future__ import annotations

import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTENT_DIR = ROOT / "content" / "articles"
DATA_FILE = ROOT / "data" / "articles.js"
SELECTOR_DIR = ROOT / "articles"
MANIFEST_FILE = ROOT / "data" / "generated-article-pages.json"

ROUTE_BY_CATEGORY = {
    "interviews": "interviews",
    "highlights": "features",
}

REQUIRED_I18N = ("title", "cardTitle", "cardSubtitle", "caption", "excerpt", "imageLabel", "body", "bio")


def load_articles():
    files = sorted(CONTENT_DIR.glob("*.json"))
    if not files:
        raise SystemExit("No article JSON files found in content/articles.")

    articles = []
    slugs = set()
    for path in files:
        with path.open("r", encoding="utf-8") as handle:
            article = json.load(handle)
        validate_article(article, path)
        if article["slug"] in slugs:
            raise SystemExit(f"Duplicate article slug: {article['slug']}")
        slugs.add(article["slug"])
        article["_source"] = str(path.relative_to(ROOT))
        articles.append(article)

    articles.sort(key=lambda item: item["date"]["iso"], reverse=True)
    return articles


def validate_article(article, path):
    required = ["slug", "version", "category", "categoryLabel", "date", "images", "seo", *REQUIRED_I18N]
    missing = [key for key in required if key not in article]
    if missing:
        raise SystemExit(f"{path}: missing fields: {', '.join(missing)}")

    if article["category"] not in ROUTE_BY_CATEGORY:
        raise SystemExit(f"{path}: unsupported category {article['category']!r}")

    if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", article["slug"]):
        raise SystemExit(f"{path}: slug must be lowercase kebab-case")

    for key in (*REQUIRED_I18N, "categoryLabel"):
        value = article[key]
        if not isinstance(value, dict) or not value.get("en") or not value.get("de"):
            raise SystemExit(f"{path}: {key} must contain non-empty en/de values")

    date = article["date"]
    if not all(date.get(key) for key in ("iso", "en", "de")):
        raise SystemExit(f"{path}: date must contain iso/en/de")

    if not isinstance(article["images"], list):
        raise SystemExit(f"{path}: images must be a list")

    for image_path in article["images"]:
        image = ROOT / image_path
        if not image.exists():
            raise SystemExit(f"{path}: image does not exist: {image_path}")

    seo = article["seo"]
    if not seo.get("description") or not seo.get("headline"):
        raise SystemExit(f"{path}: seo.description and seo.headline are required")


def runtime_article(article):
    return {
        "slug": article["slug"],
        "category": article["category"],
        "categoryLabel": article["categoryLabel"],
        "title": article["title"],
        "cardTitle": article["cardTitle"],
        "cardSubtitle": article["cardSubtitle"],
        "date": {"en": article["date"]["en"], "de": article["date"]["de"]},
        "images": article["images"],
        "caption": article["caption"],
        "excerpt": article["excerpt"],
        "imageLabel": article["imageLabel"],
        "body": article["body"],
    }


def build_registry(articles):
    runtime = [runtime_article(article) for article in articles]
    bios = {article["slug"]: article["bio"] for article in articles}
    return (
        "// GENERATED from /content/articles by scripts/build_site.py.\n"
        "// Do not edit this file directly.\n"
        "window.JAZZING_ARTICLES = "
        + json.dumps(runtime, ensure_ascii=False, indent=2)
        + ";\n\nwindow.JAZZING_ARTICLE_BIOS = "
        + json.dumps(bios, ensure_ascii=False, indent=2)
        + ";\n"
    )


def selector_script(slug):
    return f'''// GENERATED compatibility selector for direct static article pages.
(function() {{
  const slug = {json.dumps(slug)};
  const articles = window.JAZZING_ARTICLES || [];
  const index = articles.findIndex(function(article) {{
    return article.slug === slug;
  }});

  if (index > 0 && window.location.pathname !== "/" && window.location.pathname !== "/index.html") {{
    const article = articles.splice(index, 1)[0];
    articles.unshift(article);
  }}
}})();
'''


def page_type(article):
    return "Interview" if article["category"] == "interviews" else "Feature"


def route_for(article):
    return ROUTE_BY_CATEGORY[article["category"]]


def canonical_for(article):
    return f"https://jazzingffm.de/{route_for(article)}/{article['slug']}/"


def first_image(article):
    return article["images"][0] if article["images"] else ""


def bold_static_speaker(body, musician_name):
    return body.replace(
        f"<p>{musician_name}:",
        f"<p><strong>{html.escape(musician_name)}</strong>:",
    )


def static_page(article):
    slug = article["slug"]
    route = route_for(article)
    kind = page_type(article)
    name = article["cardTitle"]["en"]
    article_title = f"{name} {article['cardSubtitle']['en']}"
    canonical = canonical_for(article)
    first = first_image(article)
    first_absolute = f"https://jazzingffm.de/{first}" if first else "https://jazzingffm.de/favicon.png"
    category_label = article["categoryLabel"]["en"]
    category_active = "interviews" if article["category"] == "interviews" else "features"
    interviews_class = ' class="active"' if category_active == "interviews" else ""
    features_class = ' class="active"' if category_active == "features" else ""
    body = bold_static_speaker(article["body"]["en"], name)
    description = html.escape(article["seo"]["description"], quote=True)
    headline = article["seo"]["headline"]
    page_title = f"{name} — {kind} & Portrait | JazzingFfm"
    json_ld = json.dumps({
        "@context": "https://schema.org",
        "@type": "Article",
        "headline": headline,
        "datePublished": article["date"]["iso"],
        "mainEntityOfPage": canonical,
        "publisher": {"@type": "Organization", "name": "JazzingFfm", "url": "https://jazzingffm.de/"},
        "description": article["excerpt"]["en"],
        "image": first_absolute,
    }, ensure_ascii=False, separators=(",", ":"))

    if first:
        initial_gallery = (
            f'<div class="article-hero-image has-photo"><img src="/{html.escape(first, quote=True)}" '
            f'alt="{html.escape(article["caption"]["en"], quote=True)}" /></div>'
        )
    else:
        initial_gallery = f'<div class="article-hero-image">{html.escape(article["imageLabel"]["en"])}</div>'

    return f'''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{html.escape(page_title)}</title>
  <meta name="description" content="{description}" />
  <meta name="robots" content="index, follow" />
  <link rel="canonical" href="{canonical}" />
  <meta property="og:type" content="article" />
  <meta property="og:title" content="{html.escape(page_title, quote=True)}" />
  <meta property="og:description" content="{html.escape(article['excerpt']['en'], quote=True)}" />
  <meta property="og:url" content="{canonical}" />
  <meta property="og:image" content="{first_absolute}" />
  <link rel="icon" type="image/png" sizes="192x192" href="/favicon.png" />
  <link rel="shortcut icon" href="/favicon.ico" />
  <link rel="apple-touch-icon" href="/tab-icon.png" />
  <link rel="stylesheet" href="/css/style.css?v=caption37" />
  <link rel="stylesheet" href="/css/gallery-transition.css?v=gallery34" />
  <link rel="stylesheet" href="/css/article-caption-gap.css?v=caption38" />
  <link rel="stylesheet" href="/css/site-polish.css?v=15" />
  <link rel="stylesheet" href="/css/article-lightbox.css?v=1" />
  <script type="application/ld+json">{json_ld}</script>
</head>
<body>
  <header class="top-header">
    <div class="masthead">
      <a class="header-instagram-link" href="https://www.instagram.com/jazzingffm/" target="_blank" rel="noopener" aria-label="JazzingFfm. on Instagram"><svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg></a>
      <a class="header-logo-link" href="/" aria-label="JazzingFfm. home"><img class="header-logo" src="/header.png" alt="JazzingFfm." /></a>
      <div class="language-switch" aria-label="Language switch"><button type="button" data-lang-button="en">EN</button><button type="button" data-lang-button="de">DE</button></div>
    </div>
  </header>
  <nav class="nav-row" aria-label="Main navigation"><div class="nav-inner"><div class="nav-links">
    <a href="/" data-nav-key="home">JazzingFfm.</a><a href="/#/interviews" data-nav-key="interviews"{interviews_class}>Interviews</a><a href="/#/features" data-nav-key="features"{features_class}>Features</a><a href="/#/contact" data-nav-key="contact">Contact</a>
  </div></div></nav>
  <main>
    <section class="page active"><div class="container article-page"><article class="article-shell">
      <a id="articleCategory" class="article-category" href="/#/{route}">{html.escape(category_label)}</a>
      <h1 id="articleTitle" class="article-title">{html.escape(article_title)}</h1>
      <p id="articleByline" class="byline">{html.escape(article['date']['en'])}</p>
      <hr class="thin-line" />
      <div id="articleGallery" class="article-gallery"><div id="articleGalleryTrack" class="article-gallery-track">{initial_gallery}</div><button id="galleryPrevious" class="gallery-control previous" type="button" aria-label="Previous photo">‹</button><button id="galleryNext" class="gallery-control next" type="button" aria-label="Next photo">›</button><div id="galleryStatus" class="gallery-status" aria-live="polite"></div></div>
      <p id="articleCaption" class="caption">{html.escape(article['caption']['en'])}</p>
      <div id="articleBody" class="article-body">{body}</div>
      <aside id="articleBio" class="artist-bio" aria-labelledby="articleBioTitle"><h2 id="articleBioTitle">{html.escape(name)}</h2><p id="articleBioText">{html.escape(article['bio']['en'])}</p></aside>
    </article></div></section>
  </main>
  <footer class="site-footer"><div class="footer-main"><div class="footer-left"><div class="copyright"><p>© 2026 JAZZINGFFM. ALL RIGHTS RESERVED</p><div class="footer-meta"><p id="footerLove">MADE WITH LOVE IN FRANKFURT</p><span class="footer-separator" aria-hidden="true">•</span><nav class="footer-legal" aria-label="Legal"><a href="/impressum/">Impressum</a><span class="footer-separator" aria-hidden="true">•</span><a href="/datenschutz/">Datenschutz</a></nav></div></div></div><div class="footer-partner"><span id="footerPartnerLabel">In cooperation with</span><a href="https://www.jazz-frankfurt.de/" target="_blank" rel="noopener noreferrer" aria-label="Jazz-Initiative Frankfurt am Main e.V."><img src="/JIF_logo.png" alt="Jazz-Initiative Frankfurt am Main e.V." /></a></div></div></footer>
  <script src="/data/articles.js"></script><script src="/articles/{slug}.js?v={int(article['version'])}"></script><script src="/js/static-article.js?v=10"></script><script src="/js/article-lightbox.js?v=2"></script>
</body>
</html>
'''


def load_manifest():
    if not MANIFEST_FILE.exists():
        return []
    try:
        return json.loads(MANIFEST_FILE.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, TypeError):
        return []


def write_if_changed(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    print(f"generated {path.relative_to(ROOT)}")
    return True


def main():
    articles = load_articles()
    changed = False

    changed |= write_if_changed(DATA_FILE, build_registry(articles))

    for article in articles:
        selector_path = SELECTOR_DIR / f"{article['slug']}.js"
        changed |= write_if_changed(selector_path, selector_script(article["slug"]))

    previously_managed = set(load_manifest())
    managed = set(previously_managed)
    current_slugs = {article["slug"] for article in articles}

    for article in articles:
        target = ROOT / route_for(article) / article["slug"] / "index.html"
        if article["slug"] in previously_managed or not target.exists():
            changed |= write_if_changed(target, static_page(article))
            managed.add(article["slug"])

    for stale_slug in sorted(previously_managed - current_slugs):
        for route in ROUTE_BY_CATEGORY.values():
            stale_page = ROOT / route / stale_slug / "index.html"
            if stale_page.exists():
                stale_page.unlink()
                try:
                    stale_page.parent.rmdir()
                except OSError:
                    pass
                print(f"removed {stale_page.relative_to(ROOT)}")
                changed = True
        stale_selector = SELECTOR_DIR / f"{stale_slug}.js"
        if stale_selector.exists():
            stale_selector.unlink()
            print(f"removed {stale_selector.relative_to(ROOT)}")
            changed = True
        managed.discard(stale_slug)

    manifest = json.dumps(sorted(managed), ensure_ascii=False, indent=2) + "\n"
    changed |= write_if_changed(MANIFEST_FILE, manifest)

    if not changed:
        print("article build already up to date")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"article build failed: {exc}", file=sys.stderr)
        raise
